'use strict';

const DATA_URLS = ['philosophers.json', '/philosophers.json'];
const CAT = { on:'ontology/metaphysics', ep:'epistemology', et:'ethics', po:'politics', ae:'aesthetics', th:'theology/religion' };
const CAT_LABEL = { 'ontology/metaphysics':'Ontology', epistemology:'Knowledge', ethics:'Ethics', politics:'Politics', aesthetics:'Art', 'theology/religion':'Theology' };
const CAT_COLOR = { 'ontology/metaphysics':'var(--brown)', epistemology:'var(--blue)', ethics:'var(--green)', politics:'var(--red)', aesthetics:'var(--violet)', 'theology/religion':'var(--gold)' };
const CAT_ORDER = Object.keys(CAT_LABEL);
const ROUTES = [
  {id:'time', title:'Time / Change', icon:'◷', keys:['time','change','becoming','flux','eternal','duration','present','space'], thesis:'From cosmology to metaphysics, experience, history, and finitude.'},
  {id:'limits', title:'Limits of Knowledge', icon:'○', keys:['knowledge','truth','certainty','doubt','experience','perception','logic','science','fallible','senses'], thesis:'Knowledge becomes rigorous by discovering its limits.'},
  {id:'art', title:'Art / Representation', icon:'◇', keys:['art','aesthetics','beauty','poetry','tragedy','representation','history','image','illusion'], thesis:'Art moves from imitation to catharsis, critique, simulation, and self-exposure.'},
  {id:'language', title:'Language / Meaning', icon:'⌁', keys:['language','words','speech','writing','meaning','sign','reference','symbol','discourse'], thesis:'Meaning shifts from representation to systems, use, reference, force, and discourse.'},
  {id:'power', title:'Power / State', icon:'□', keys:['power','government','state','law','society','rights','freedom','public','justice','authority'], thesis:'Political order moves through sovereignty, rights, liberty, ideology, discipline, and justice.'},
  {id:'gender', title:'Gender / Identity', icon:'◐', keys:['gender','women','woman','female','male','body','sex','identity','feminist'], thesis:'Gender moves from natural hierarchy to equality, embodiment, discourse, and performativity.'},
  {id:'god', title:'God / Religion', icon:'✶', keys:['god','religion','faith','soul','evil','divine','theology'], thesis:'God as cause, guarantee, order, projection, problem, and critique.'},
  {id:'mind', title:'Mind / Self', icon:'◉', keys:['mind','body','soul','self','consciousness','experience','subject','psychology'], thesis:'Self as soul, subject, bundle, will, unconscious, body, language, computation.'}
];

const $ = (s, r=document) => r.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const uniq = xs => [...new Set(xs.filter(Boolean))];
const count = xs => Object.entries(xs.reduce((a,x)=>(x&&(a[x]=(a[x]||0)+1),a),{})).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));
const clamp = (v,a,b) => Math.max(a, Math.min(b, v));

let DB = null;
let S = { view:'map', q:'', concept:null, question:null, domain:null, person:null, relation:'all', sort:'chrono', route:'time', rail:'concepts', statement:null };

boot();

async function boot(){
  $('#q').addEventListener('input', e => { S.q = e.target.value.trim(); render(); });
  $('#theme').onclick = () => { const a=$('#app'); a.dataset.theme = a.dataset.theme === 'dark' ? 'light' : 'dark'; };
  $('#reset').onclick = reset;
  document.addEventListener('click', handleClick);
  try { setDB(buildDB(await loadJSON())); } catch(e) { $('#content').innerHTML = `<div class="empty">${esc(e.message)}</div>`; }
}
async function loadJSON(){
  let err;
  for (const url of DATA_URLS) {
    try { const r = await fetch(url, {cache:'no-store'}); if(!r.ok) throw new Error(`${r.status} ${url}`); return await r.json(); }
    catch(e){ err=e; }
  }
  throw err || new Error('Missing philosophers.json');
}
function handleClick(e){
  const el = e.target.closest('[data-act]'); if(!el || !DB) return;
  const {act,val,kind} = el.dataset;
  if(act==='view'){ S.view=val; S.statement=null; render(); }
  if(act==='rail'){ S.rail=val; render(); }
  if(act==='sort'){ S.sort=val; render(); }
  if(act==='relation'){ S.relation = S.relation===val && val!=='all' ? 'all' : val; render(); }
  if(act==='route'){ S.route=val; S.view='routes'; render(); }
  if(act==='filter') toggleFilter(kind,val);
  if(act==='clear') clearFilter(val);
  if(act==='statement'){ S.statement=Number(val); inspectStatement(S.statement); if(S.view==='map') requestAnimationFrame(drawGraph); }
  if(act==='person'){ toggleFilter('person', val); inspectPerson(Number(val)); }
  if(act==='inspectConcept') inspectConcept(val);
  if(act==='inspectQuestion') inspectQuestion(val);
  if(act==='inspectDomain') inspectDomain(val);
}
function reset(){ S={...S,q:'',concept:null,question:null,domain:null,person:null,relation:'all',sort:'chrono',statement:null}; $('#q').value=''; render(); inspectOverview(); }
function toggleFilter(kind,val){
  if(kind==='concept') S.concept = S.concept===val ? null : val;
  if(kind==='question') S.question = S.question===val ? null : val;
  if(kind==='domain') S.domain = S.domain===val ? null : val;
  if(kind==='person') S.person = S.person===Number(val) ? null : Number(val);
  S.statement=null; render();
}
function clearFilter(k){ if(k==='q'){S.q='';$('#q').value='';} else S[k]=null; render(); }

function buildDB(raw){
  if(!raw?.people || !raw?.records || !raw?.links) throw new Error('Invalid philosophers.json');
  const people = raw.people.map(p => ({...p, year:yearOf(p.time), movement:movementOf(p)}));
  const peopleById = Object.fromEntries(people.map(p => [p.id,p]));
  const statements = raw.records.map(r => {
    const p = peopleById[r.person] || {id:r.person,name:`Person ${r.person}`,time:'',movement:'unknown',year:null};
    const domains = (r.cats||[]).map(c => CAT[c] || c);
    const concepts = inferConcepts(r.line, domains);
    const questions = inferQuestions(r.line, domains, concepts);
    const s = {id:r.id, personId:r.person, person:p.name, time:p.time||'', year:p.year, order:r.order||'', text:r.line||'', reference:r.reference||'', domains, concepts, questions, movement:p.movement, summary:summaryFor(r.line, domains)};
    s.search = [s.text,s.person,s.time,s.movement,s.summary,...domains,...concepts,...questions].join(' ').toLowerCase();
    return s;
  });
  const byId = Object.fromEntries(statements.map(s => [s.id,s]));
  const relations = raw.links.filter(l=>byId[l.l0]&&byId[l.l1]).map((l,i)=>({id:i, source:l.l0, target:l.l1, type:l.type==='p'?'support':'challenge'}));
  const db = {people, statements, relations, peopleById, byId, byPerson:{}, out:{}, in:{}};
  statements.forEach(s => (db.byPerson[s.personId] ||= []).push(s));
  relations.forEach(r => { (db.out[r.source] ||= []).push(r); (db.in[r.target] ||= []).push(r); });
  db.concepts = count(statements.flatMap(s=>s.concepts)).map(([name,n])=>({name,count:n}));
  db.questions = count(statements.flatMap(s=>s.questions)).map(([name,n])=>({name,count:n}));
  db.domains = count(statements.flatMap(s=>s.domains)).map(([name,n])=>({name,count:n}));
  db.routes = ROUTES.map(r => ({...r, ids: statements.filter(s=>r.keys.some(k=>s.search.includes(k))).sort(sortChrono).map(s=>s.id)}));
  return db;
}
function setDB(db){ DB=db; $('#q').placeholder=`Search ${db.people.length} authors, ${db.statements.length} postulates, ${db.relations.length} links, concepts, problems…`; render(); inspectOverview(); }

function yearOf(t=''){ const m=String(t).match(/\d+/); if(!m) return null; let y=Number(m[0]); return String(t).includes('BC') ? -y : y; }
function movementOf(p){ const n=p.name, y=yearOf(p.time); if(['Thales','Anaximander','Anaximenes'].includes(n))return'presocratic/cosmology'; if(n==='Pythagoras')return'pythagorean/number'; if(n==='Heraclitus')return'presocratic/becoming'; if(['Parmenides','Zeno of Elea'].includes(n))return'eleatic/being'; if(['Leucippus & Democritus','Epicurus'].includes(n))return'atomism/materialism'; if(n==='Socrates')return'socratic/ethics'; if(n==='Plato')return'platonic/forms'; if(n==='Aristotle')return'aristotelian/worldliness'; if(y<1700)return'early modern/metaphysics'; if(y<1800)return'enlightenment/empiricism politics'; if(y<1870)return'nineteenth/history critique'; if(y<1930)return'modern/language science'; return'contemporary/analytic continental'; }
function inferConcepts(text='',domains=[]){ const l=String(text).toLowerCase(), out=[]; const add=(c,rx)=>{if(rx.test(l))out.push(c)}; add('time',/\btime\b|timeless|eternal|present|duration|tempor/);add('change',/change|flux|becoming|evolv|process/);add('nature',/nature|natural|world|universe|earth|species/);add('matter',/matter|material|atom|particle|body|corporeal/);add('space',/space|location|world|universe/);add('mind',/mind|mental|conscious|intellect|thought|subject|awareness/);add('body',/body|corporeal|brain/);add('self',/self|subject|identity|person|soul/);add('reason',/reason|rational|logic|mathemat|proof|deduc/);add('experience',/experience|sens|observ|perception|empirical|impression/);add('knowledge',/knowledge|know|truth|certainty|doubt|belief/);add('truth',/truth|true|false|certainty|proof/);add('science',/science|scientific|experiment|method|hypothesis|theory/);add('language',/language|word|speech|writing|sign|symbol|meaning|reference|discourse/);add('art',/art|aesthetic|beauty|poetry|tragedy|image|representation|sublime|illusion/);add('history',/history|historical|past|civilization|tradition/);add('religion',/god|divine|religion|faith|soul|evil|theology/);add('morality',/moral|virtue|good|evil|right|wrong|duty/);add('justice',/justice|injustice|rights|law|equality|fair/);add('society',/society|social|community|public|private|civilization/);add('government',/government|state|authority|sovereign|law|politic|citizen/);add('power',/power|authority|dominat|control|discipline|govern/);add('freedom',/freedom|free|liberty|will|choice|necessity/);add('death',/death|mortality|die/);add('desire',/desire|passion|pleasure|emotion|fear|drive/);add('gender',/women|woman|female|male|gender|sex|femin/);add('math',/math|number|geometry|calculation/);add('causality',/cause|effect|causal|causation/); if(domains.includes('aesthetics'))out.push('art'); if(domains.includes('politics'))out.push('society','government'); if(domains.includes('theology/religion'))out.push('religion'); return uniq(out); }
function inferQuestions(line='',domains=[],concepts=[]){ const t=new Set(concepts), d=new Set(domains), out=[]; const add=x=>{if(!out.includes(x))out.push(x)}; if(d.has('ontology/metaphysics')||['nature','matter','space','mind','body','self','causality'].some(x=>t.has(x)))add('What exists?'); if(d.has('epistemology')||['knowledge','truth','reason','experience','science','language'].some(x=>t.has(x)))add('How can we know?'); if(d.has('ethics')||['morality','justice','death','desire','freedom'].some(x=>t.has(x)))add('How should one live?'); if(d.has('politics')||['society','government','power'].some(x=>t.has(x)))add('How should society be governed?'); if(d.has('aesthetics')||t.has('art'))add('What does art do?'); if(d.has('theology/religion')||t.has('religion'))add('What is God?'); if(t.has('time')||t.has('change'))add('What is time?'); if(t.has('language'))add('What does language mean?'); if(t.has('science'))add('What is science?'); if(t.has('gender'))add('What is gender?'); if(t.has('freedom'))add('What is freedom?'); if(t.has('mind'))add('What is mind?'); return out.length?out.slice(0,5):['What is at stake?']; }
function summaryFor(line='',domains=[]){ const l=String(line).toLowerCase(); for(const [rx,g] of [[/time|change|flux|becoming|eternal/,'reality read through becoming'],[/language|word|speech|sign|meaning|discourse/,'meaning mediated by signs'],[/art|beauty|poetry|tragedy|image|illusion/,'representation tests reality'],[/science|experiment|method|theory/,'knowledge disciplined by method'],[/gender|women|female|male|sex/,'identity made philosophically visible'],[/government|state|power|law|society/,'order explained through power'],[/god|religion|faith|soul|evil/,'divinity anchors the system'],[/reason|logic|math|proof/,'reason seeks stable form'],[/experience|sense|observ|perception/,'knowledge begins at its limit'],[/death|mortality/,'death reframes value'],[/freedom|liberty|will/,'freedom tested by necessity'],[/truth|certainty|doubt/,'truth tested by doubt'],[/nature|matter|atom/,'nature becomes explanatory ground']]) if(rx.test(l)) return g; if(domains.includes('ethics'))return'thought becomes a rule of life'; if(domains.includes('epistemology'))return'knowledge defined by its conditions'; if(domains.includes('ontology/metaphysics'))return'being reduced to first principles'; return'claim positioned in the map'; }
function sortChrono(a,b){ return (a.year??0)-(b.year??0)||a.person.localeCompare(b.person)||Number(a.order||0)-Number(b.order||0); }
function rels(id){ return [...(DB.out[id]||[]), ...(DB.in[id]||[])]; }
function score(s){ return rels(s.id).length; }
function sorter(a,b){ if(S.sort==='author') return a.person.localeCompare(b.person)||Number(a.order||0)-Number(b.order||0); if(S.sort==='impact') return score(b)-score(a)||sortChrono(a,b); return sortChrono(a,b); }
function visible(){ const q=S.q.toLowerCase(); return DB.statements.filter(s=>{ if(S.person && s.personId!==S.person)return false; if(S.concept && !s.concepts.includes(S.concept))return false; if(S.question && !s.questions.includes(S.question))return false; if(S.domain && !s.domains.includes(S.domain))return false; if(S.relation!=='all' && !rels(s.id).some(r=>r.type===S.relation))return false; return !q || s.search.includes(q); }).sort(sorter); }

function render(){ if(!DB)return; const st=visible(); $('#sub').textContent=`${st.length} visible · ${count(st.map(s=>s.person)).length} authors · ${count(st.flatMap(s=>s.concepts)).length} concepts`; renderRail(st); const views={map:viewMap,all:viewAll,routes:viewRoutes,impact:viewImpact,concepts:viewConcepts,compare:viewCompare,upload:viewUpload}; $('#content').innerHTML=(views[S.view]||viewMap)(st); $('#mobileNav').innerHTML=nav(true); attachUpload(); if(S.view==='map') requestAnimationFrame(drawGraph); if(!S.statement) inspectOverview(st); }
function nav(mobile=false){ const items=mobile?[['map','Map','·'],['all','All','¶'],['routes','Routes','→'],['impact','Impact','±'],['concepts','Ideas','#']]:[['map','Map','·'],['all','All','¶'],['routes','Routes','→'],['impact','Impact','±'],['concepts','Ideas','#'],['compare','Compare','∥'],['upload','Upload','↑']]; return items.map(([id,t,ico])=>`<button class="nav ${S.view===id?'active':''}" data-act="view" data-val="${id}"><i>${ico}</i>${t}</button>`).join(''); }
function renderRail(st){ const filters=[]; if(S.q)filters.push(token('search',S.q,'q')); if(S.person)filters.push(token('author',DB.peopleById[S.person]?.name,'person')); if(S.concept)filters.push(token('concept',pretty(S.concept),'concept')); if(S.question)filters.push(token('question',S.question,'question')); if(S.domain)filters.push(token('domain',CAT_LABEL[S.domain]||pretty(S.domain),'domain')); $('#rail').innerHTML=`<div class="section"><div class="label">Navigate</div><div class="navGrid">${nav(false)}</div></div><div class="section"><div class="subLabel">Filters</div><div class="tokens">${filters.join('')||'<span class="subLabel">none</span>'}</div><div class="tabs" style="margin-top:7px"><button class="chip ${S.relation==='all'?'active':''}" data-act="relation" data-val="all">all</button><button class="chip ${S.relation==='support'?'active':''}" data-act="relation" data-val="support">+ supports</button><button class="chip ${S.relation==='challenge'?'active':''}" data-act="relation" data-val="challenge">− challenges</button></div></div><div class="section"><div class="subLabel">Sort</div><div class="tabs"><button class="chip ${S.sort==='chrono'?'active':''}" data-act="sort" data-val="chrono">chrono</button><button class="chip ${S.sort==='author'?'active':''}" data-act="sort" data-val="author">author</button><button class="chip ${S.sort==='impact'?'active':''}" data-act="sort" data-val="impact">impact</button></div></div><div class="section"><div class="subLabel">Browse</div><div class="tabs"><button class="chip ${S.rail==='authors'?'active':''}" data-act="rail" data-val="authors">authors</button><button class="chip ${S.rail==='concepts'?'active':''}" data-act="rail" data-val="concepts">concepts</button><button class="chip ${S.rail==='questions'?'active':''}" data-act="rail" data-val="questions">questions</button><button class="chip ${S.rail==='domains'?'active':''}" data-act="rail" data-val="domains">domains</button></div></div>${railList(st)}`; }
function token(label,val,key){ return `<button class="token" data-act="clear" data-val="${key}"><b>${esc(label)} · ${esc(val)}</b><span>×</span></button>`; }
function railList(st){ if(S.rail==='authors')return list('Authors in view', count(st.map(s=>s.person)).slice(0,24).map(([name,n])=>{const p=DB.people.find(x=>x.name===name); return row(name,n,'person',p?.id)})); if(S.rail==='concepts')return list('Concepts in view', count(st.flatMap(s=>s.concepts)).slice(0,32).map(([name,n])=>row(pretty(name),n,'concept',name))); if(S.rail==='questions')return list('Questions in view', count(st.flatMap(s=>s.questions)).slice(0,24).map(([name,n])=>row(name,n,'question',name))); return list('Domains', DB.domains.map(d=>row(CAT_LABEL[d.name]||pretty(d.name),d.count,'domain',d.name))); }
function list(title, rows){ return `<div class="section"><div class="subLabel">${esc(title)}</div><div class="list">${rows.join('')}</div></div>`; }
function row(label,n,kind,val){ const active=(kind==='person'&&S.person===Number(val))||(kind==='concept'&&S.concept===val)||(kind==='question'&&S.question===val)||(kind==='domain'&&S.domain===val); return `<button class="row ${active?'active':''}" data-act="filter" data-kind="${kind}" data-val="${esc(val)}"><b>${esc(label)}</b><span>${n}</span></button>`; }

function viewMap(st){ return `<div class="grid two"><div class="card"><div class="subLabel">Map</div><div class="graph"><svg id="graph"></svg></div></div><div class="grid"><div class="card"><div class="subLabel">Concepts</div><div class="heat">${heat(count(st.flatMap(s=>s.concepts)).slice(0,16),'concept')}</div></div><div class="card"><div class="subLabel">Questions</div><div class="heat">${heat(count(st.flatMap(s=>s.questions)).slice(0,12),'question')}</div></div></div></div><div class="masonry" style="margin-top:10px">${st.slice(0,120).map(s=>`<div class="tile">${claim(s)}</div>`).join('')}</div>`; }
function viewAll(st){ if(S.person) return authorView(DB.peopleById[S.person], st); return `<div class="masonry">${st.map(s=>`<div class="tile">${claim(s)}</div>`).join('')||empty('No postulates match.')}</div>`; }
function authorView(p, st){ return `<div class="hero"><div class="heroTop"><h2>${esc(p.name)}</h2><span class="date">${esc(p.time)}</span></div><div class="intro"><span class="summary">${esc(p.movement)} · ${st.length} filtered postulates</span>${topConcept(st)}</div></div><div class="compactList">${st.map(s=>compact(s,true)).join('')}</div>`; }
function viewRoutes(){ const r=DB.routes.find(x=>x.id===S.route)||DB.routes[0]; const st=r.ids.map(id=>DB.byId[id]).filter(matchesActive).sort(sortChrono); const byAuthor=Object.values(st.reduce((a,s)=>((a[s.person]||=[]).push(s),a),{})).sort((a,b)=>sortChrono(a[0],b[0])); return `<div class="card" style="margin-bottom:10px"><div class="subLabel">Route</div><div class="tabs">${DB.routes.map(x=>`<button class="chip ${x.id===r.id?'active':''}" data-act="route" data-val="${x.id}">${esc(x.icon)} ${esc(x.title)}</button>`).join('')}</div><p style="margin-top:8px">${esc(r.thesis)}</p></div><div class="routeLine">${byAuthor.map(g=>`<div class="routeStep card"><div class="claimTop"><b>${esc(g[0].person)}</b><span class="date">${esc(g[0].time)}</span></div><div class="postulates">${g.map(s=>`<button class="postulate" data-act="statement" data-val="${s.id}">${esc(s.text)}</button>`).join('')}</div></div>`).join('')}</div>`; }
function viewImpact(st){ const ranked=[...st].sort((a,b)=>score(b)-score(a)||sortChrono(a,b)).slice(0,160); return `<div class="masonry">${ranked.map(s=>`<div class="tile">${claim(s,true)}</div>`).join('')}</div>`; }
function viewConcepts(st){ const domains=DB.domains, concepts=count(st.flatMap(s=>s.concepts)).slice(0,30), qs=count(st.flatMap(s=>s.questions)).slice(0,14); return `<div class="grid two"><div class="card"><div class="subLabel">Domains</div><div class="heat">${domains.map(d=>heatItem(CAT_LABEL[d.name]||pretty(d.name),d.count,'domain',d.name)).join('')}</div></div><div class="card"><div class="subLabel">Questions</div><div class="heat">${qs.map(([n,c])=>heatItem(n,c,'question',n)).join('')}</div></div></div><div class="card" style="margin-top:10px"><div class="subLabel">Concepts</div><div class="heat">${concepts.map(([n,c])=>heatItem(pretty(n),c,'concept',n)).join('')}</div></div><div class="masonry" style="margin-top:10px">${st.slice(0,140).map(s=>`<div class="tile">${claim(s)}</div>`).join('')}</div>`; }
function viewCompare(){ const people=(S.person?[DB.peopleById[S.person]]:DB.people.slice(10,14)); return `<div class="masonry">${people.map(p=>`<div class="tile"><div class="card"><div class="claimTop"><b>${esc(p.name)}</b><span class="date">${esc(p.time)}</span></div>${(DB.byPerson[p.id]||[]).filter(matchesActive).slice(0,12).map(s=>compact(s,false)).join('')}</div></div>`).join('')}</div>`; }
function viewUpload(){ return `<div class="card"><div class="subLabel">Upload</div><div class="drop"><input id="fileInput" type="file" accept=".json,application/json"></div></div>`; }

function heat(items,kind){ const max=Math.max(1,...items.map(x=>x[1])); return items.map(([name,n])=>heatItem(kind==='concept'?pretty(name):name,n,kind,name,max)).join(''); }
function heatItem(label,n,kind,val,max=1){ return `<button data-act="filter" data-kind="${kind}" data-val="${esc(val)}"><b>${esc(label)}</b><p>${n} postulates</p><div class="bar"><i style="width:${Math.round(n/max*100)}%"></i></div></button>`; }
function claim(s,showImpact=false){ const rs=rels(s.id); const concepts=s.concepts.slice(0,3).map(pretty).join('  '); return `<article class="claim" data-act="statement" data-val="${s.id}"><div class="claimTop"><div class="author"><b>${esc(s.person)}</b></div><div class="date">${esc(s.time)}${showImpact?` · ${rs.length} links`:''}</div></div><div class="intro"><span class="summary">${esc(s.summary)}</span>${concepts?`<button class="mono inspectable" data-act="inspectConcept" data-val="${esc(s.concepts[0])}">${esc(concepts)}</button>`:''}</div><div class="text">${esc(s.text)}</div><div class="taxonomy"><div class="tax"><div class="taxLabel">Domain</div><div class="domains">${s.domains.map(d=>domain(d,true)).join('')}</div></div><div class="tax"><div class="taxLabel">Asks</div><div class="questions">${s.questions.slice(0,3).map(q=>`<button class="question inspectable" data-act="inspectQuestion" data-val="${esc(q)}">${esc(q)}</button>`).join('')}</div></div></div>${rs.length?`<div class="rels">${rs.slice(0,4).map(r=>relation(r,s.id)).join('')}</div>`:''}</article>`; }
function compact(s,withRelations=false){ const concepts=s.concepts.slice(0,4).map(pretty).join('  '); return `<button class="compact" data-act="statement" data-val="${s.id}"><div class="intro"><span class="summary">${esc(s.summary)}</span>${concepts?`<span class="mono">${esc(concepts)}</span>`:''}</div><div class="text">${esc(s.text)}</div>${withRelations?`<div class="rels">${rels(s.id).slice(0,3).map(r=>relation(r,s.id)).join('')}</div>`:''}</button>`; }
function relation(r,focus){ const o=DB.byId[r.source===focus?r.target:r.source]; return `<button class="relation ${r.type}" data-act="statement" data-val="${o.id}"><span class="mark">${r.type==='support'?'+':'−'}</span><span><b>${esc(o.person)}</b> — ${esc(o.text)}</span></button>`; }
function domain(d,click=false){ return `<${click?'button':'span'} class="domain inspectable" ${click?`data-act="inspectDomain" data-val="${esc(d)}"`:''}><i style="background:${CAT_COLOR[d]||'var(--muted)'}"></i>${esc(CAT_LABEL[d]||pretty(d))}</${click?'button':'span'}>`; }
function topConcept(st){ const t=count(st.flatMap(s=>s.concepts))[0]; return t?`<span class="mono">${esc(pretty(t[0]))}</span>`:''; }
function pretty(s){ return String(s).replaceAll('_',' ').replaceAll('/',' · '); }
function empty(t){ return `<div class="empty">${esc(t)}</div>`; }

function drawGraph(){ const svg=$('#graph'); if(!svg)return; const st=visible().slice(0,240), ids=new Set(st.map(s=>s.id)); let rs=DB.relations.filter(r=>ids.has(r.source)&&ids.has(r.target)); if(S.relation!=='all')rs=rs.filter(r=>r.type===S.relation); const w=svg.clientWidth||900,h=svg.clientHeight||420, years=DB.people.map(p=>p.year).filter(Number.isFinite), min=Math.min(...years), max=Math.max(...years), span=max-min||1, bands=Object.fromEntries(CAT_ORDER.map((c,i)=>[c,(i+1)/(CAT_ORDER.length+1)])), pos={}; st.forEach((s,i)=>{const x=32+(((s.year??0)-min)/span)*(w-64), y=(bands[s.domains[0]]||.55)*h+((i%9)-4)*4.4; pos[s.id]=[clamp(x,18,w-18),clamp(y,18,h-18)];}); svg.innerHTML=rs.slice(0,460).map(r=>{const a=pos[r.source],b=pos[r.target];return a&&b?`<line class="edge ${r.type}" x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/>`:''}).join('')+st.map(s=>{const [x,y]=pos[s.id]; return `<g data-act="statement" data-val="${s.id}"><circle cx="${x}" cy="${y}" r="${S.statement===s.id?6.5:4}" fill="${CAT_COLOR[s.domains[0]]||'var(--ink)'}"><title>${esc(s.person)} — ${esc(s.text)}</title></circle></g>`;}).join('')+uniq(st.map(s=>s.personId)).slice(0,70).map(id=>{const s=st.find(x=>x.personId===id),p=pos[s.id]; return `<text class="svglabel" x="${p[0]+6}" y="${p[1]-6}">${esc(s.person)}</text>`;}).join(''); }

function inspectOverview(st=visible()){ $('#context').innerHTML=`<div class="card"><div class="subLabel">Current view</div><div class="heat"><button><b>${st.length}</b><p>postulates</p></button><button><b>${count(st.map(s=>s.person)).length}</b><p>authors</p></button><button><b>${count(st.flatMap(s=>s.concepts)).length}</b><p>concepts</p></button></div></div>`; }
function inspectPerson(id){ const p=DB.peopleById[id], st=(DB.byPerson[id]||[]).filter(matchesActive); $('#context').innerHTML=`<div class="card"><div class="claimTop"><h3>${esc(p.name)}</h3><span class="date">${esc(p.time)}</span></div><div class="intro"><span class="summary">${esc(p.movement)} · ${st.length} filtered postulates</span>${topConcept(st)}</div></div><div class="card" style="margin-top:10px"><div class="subLabel">Postulates</div><div class="postulates">${st.slice(0,18).map(s=>`<button class="postulate" data-act="statement" data-val="${s.id}">${esc(s.text)}</button>`).join('')}</div></div>`; }
function inspectStatement(id){ const s=DB.byId[id]; S.statement=id; $('#context').innerHTML=`<div class="card"><div class="claimTop"><h3>${esc(s.person)}</h3><span class="date">${esc(s.time)}</span></div><div class="intro"><span class="summary">${esc(s.summary)}</span>${s.concepts[0]?`<span class="mono">${esc(pretty(s.concepts[0]))}</span>`:''}</div><div class="text">${esc(s.text)}</div></div><div class="card" style="margin-top:10px"><div class="subLabel">Semantics</div><div class="taxonomy"><div class="tax"><div class="taxLabel">Domain</div><div>${s.domains.map(d=>domain(d,true)).join('')}</div></div><div class="tax"><div class="taxLabel">Ideas</div><div>${s.concepts.map(c=>`<button class="mono inspectable" data-act="inspectConcept" data-val="${esc(c)}">${esc(pretty(c))}</button>`).join('')}</div></div><div class="tax"><div class="taxLabel">Asks</div><div>${s.questions.map(q=>`<button class="question inspectable" data-act="inspectQuestion" data-val="${esc(q)}">${esc(q)}</button>`).join('')}</div></div></div></div><div class="card" style="margin-top:10px"><div class="subLabel">Relations</div><div class="rels">${rels(id).map(r=>relation(r,id)).join('')||'<p>None.</p>'}</div></div>`; }
function collapsible(st){ const groups=Object.values(st.reduce((a,s)=>((a[s.person]||=[]).push(s),a),{})).sort((a,b)=>sortChrono(a[0],b[0])); return groups.map(g=>`<details class="accordion"><summary><b>${esc(g[0].person)}</b><span>${esc(g[0].time)} · ${g.length}</span></summary><div class="postulates">${g.map(s=>`<button class="postulate" data-act="statement" data-val="${s.id}">${esc(s.text)}</button>`).join('')}</div></details>`).join(''); }
function inspectConcept(name){ const st=DB.statements.filter(s=>s.concepts.includes(name)); $('#context').innerHTML=`<div class="card"><div class="claimTop"><h3>${esc(pretty(name))}</h3><span class="date">${st.length}</span></div><p>${count(st.map(s=>s.person)).length} authors · ${count(st.flatMap(s=>s.questions)).length} questions</p></div><div class="card" style="margin-top:10px"><div class="subLabel">Authors / postulates</div>${collapsible(st)}</div>`; }
function inspectQuestion(name){ const st=DB.statements.filter(s=>s.questions.includes(name)); $('#context').innerHTML=`<div class="card"><div class="claimTop"><h3>${esc(name)}</h3><span class="date">${st.length}</span></div><p>${count(st.map(s=>s.person)).length} authors · ${count(st.flatMap(s=>s.concepts)).length} concepts</p></div><div class="card" style="margin-top:10px"><div class="subLabel">Authors / postulates</div>${collapsible(st)}</div>`; }
function inspectDomain(name){ const st=DB.statements.filter(s=>s.domains.includes(name)); $('#context').innerHTML=`<div class="card"><div class="claimTop"><h3>${esc(CAT_LABEL[name]||pretty(name))}</h3><span class="date">${st.length}</span></div><p>${count(st.map(s=>s.person)).length} authors</p></div><div class="card" style="margin-top:10px"><div class="subLabel">Authors / postulates</div>${collapsible(st)}</div>`; }
function uploadBox(){return`<div class="drop"><input id="fileInput" type="file" accept=".json,application/json"></div>`} function attachUpload(){const input=$('#fileInput'); if(input) input.onchange=async e=>{const f=e.target.files[0]; if(!f)return; try{setDB(buildDB(JSON.parse(await f.text())))}catch(err){alert(err.message)}};}
