'use strict';

const DATA_URLS = ['philosophers.json', '/philosophers.json'];
const CAT = { on:'ontology/metaphysics', ep:'epistemology', et:'ethics', po:'politics', ae:'aesthetics', th:'theology/religion' };
const CAT_ORDER = ['ontology/metaphysics','epistemology','ethics','politics','aesthetics','theology/religion'];
const CAT_LABEL = { 'ontology/metaphysics':'Ontology', epistemology:'Knowledge', ethics:'Ethics', politics:'Politics', aesthetics:'Art', 'theology/religion':'Theology' };
const CAT_COLOR = { 'ontology/metaphysics':'var(--brown)', epistemology:'var(--blue)', ethics:'var(--green)', politics:'var(--red)', aesthetics:'var(--violet)', 'theology/religion':'var(--gold)' };
const ROUTES = [
  {id:'time', title:'Time / Change', keys:['time','change','becoming','flux','eternal','duration','present','space'], thesis:'From cosmology to metaphysics, experience, history, and finitude.'},
  {id:'limits', title:'Limits of Knowledge', keys:['knowledge','truth','certainty','doubt','experience','perception','logic','science','fallible','senses'], thesis:'Knowledge becomes rigorous by discovering its limits.'},
  {id:'art', title:'Art / Representation', keys:['art','aesthetics','beauty','poetry','tragedy','representation','history','image','illusion'], thesis:'Art moves from imitation to catharsis, critique, simulation, and self-exposure.'},
  {id:'language', title:'Language / Meaning', keys:['language','words','speech','writing','meaning','sign','reference','symbol','discourse'], thesis:'Meaning shifts from representation to systems, use, reference, force, and discourse.'},
  {id:'power', title:'Power / State / Society', keys:['power','government','state','law','society','rights','freedom','public','justice','authority'], thesis:'Political order moves through sovereignty, rights, liberty, ideology, discipline, and justice.'},
  {id:'gender', title:'Gender / Sex / Identity', keys:['gender','women','woman','female','male','body','sex','identity','feminist'], thesis:'Gender moves from natural hierarchy to equality, embodiment, discourse, and performativity.'},
  {id:'god', title:'God / Religion', keys:['god','religion','faith','soul','evil','divine','theology'], thesis:'God as cause, guarantee, order, projection, problem, and critique.'},
  {id:'mind', title:'Mind / Body / Self', keys:['mind','body','soul','self','consciousness','experience','subject','psychology'], thesis:'Self as soul, subject, bundle, will, unconscious, body, language, computation.'}
];

const $ = (s, r=document) => r.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const uniq = xs => [...new Set(xs.filter(Boolean))];
const counts = xs => Object.entries(xs.reduce((a,x)=>(x&&(a[x]=(a[x]||0)+1),a),{})).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));
const clamp = (v,a,b) => Math.max(a, Math.min(b, v));

let DB = null;
let S = { view:'atlas', q:'', concept:null, problem:null, route:'time', person:null, statement:null, indexType:'concept', indexKey:null, compare:[], relation:'all', sort:'chrono' };

boot();

async function boot(){
  wire();
  try { setDB(buildDB(await loadLocalJSON())); }
  catch (err) { $('#content').innerHTML = `<div class="empty"><b>Could not load philosophers.json.</b><p>${esc(err.message)}</p></div>`; $('#context').innerHTML = uploadBox(); attachUpload(); }
}
async function loadLocalJSON(){
  let last;
  for (const url of DATA_URLS) {
    try { const r = await fetch(url, {cache:'no-store'}); if (!r.ok) throw new Error(`${r.status} ${url}`); return await r.json(); }
    catch(e){ last = e; }
  }
  throw last || new Error('Missing philosophers.json');
}
function wire(){
  $('#q').addEventListener('input', e => { S.q = e.target.value.trim(); render(); });
  $('#theme').onclick = () => { const app=$('#app'); app.dataset.theme = app.dataset.theme === 'dark' ? 'light' : 'dark'; };
  $('#reset').onclick = reset;
  document.addEventListener('click', e => {
    const el = e.target.closest('[data-act]'); if (!el || !DB) return;
    const a=el.dataset.act, v=el.dataset.val, k=el.dataset.kind;
    if (a==='view') { S.view=v; if(k) S.indexType=k; render(); }
    if (a==='filter') applyFilter(k,v);
    if (a==='clear') clear(v);
    if (a==='person') { S.person=Number(v); S.statement=null; S.view='postulates'; render(); inspectPerson(Number(v)); }
    if (a==='statement') { S.statement=Number(v); inspectStatement(Number(v)); if(S.view==='atlas'||S.view==='graph') requestAnimationFrame(drawGraph); }
    if (a==='index') { S.indexType=k; S.indexKey=v; if(k==='concept') S.concept=v; if(k==='problem') S.problem=v; S.view='index'; render(); }
    if (a==='route') { S.route=v; S.view='routes'; render(); }
    if (a==='compare') { if(!S.compare.includes(Number(v))) S.compare.push(Number(v)); S.compare=S.compare.slice(-4); S.view='compare'; render(); }
    if (a==='dropCompare') { S.compare=S.compare.filter(id=>id!==Number(v)); render(); }
    if (a==='relation') { S.relation=v; render(); }
    if (a==='sort') { S.sort=v; render(); }
  });
}
function reset(){ S={...S,q:'',concept:null,problem:null,person:null,statement:null,indexKey:null,relation:'all',sort:'chrono'}; $('#q').value=''; render(); inspectOverview(); }
function applyFilter(kind,val){ if(kind==='concept'){S.concept=val;S.indexType='concept';S.indexKey=val;} if(kind==='problem'){S.problem=val;S.indexType='problem';S.indexKey=val;} S.statement=null; S.view='index'; render(); }
function clear(key){ if(key==='q'){S.q='';$('#q').value='';} if(key==='concept')S.concept=null; if(key==='problem')S.problem=null; if(key==='person')S.person=null; if(key==='statement')S.statement=null; render(); }

function buildDB(raw){
  if(!raw||!Array.isArray(raw.people)||!Array.isArray(raw.records)||!Array.isArray(raw.links)) throw new Error('philosophers.json must contain people, records, links.');
  const people=raw.people.map(p=>({...p,year:yearOf(p.time),movement:movementOf(p)}));
  const peopleById=Object.fromEntries(people.map(p=>[p.id,p]));
  const statements=raw.records.map(r=>{
    const p=peopleById[r.person]||{id:r.person,name:`Person ${r.person}`,time:'',loc:'',movement:'unknown',year:null};
    const categories=(r.cats||[]).map(c=>CAT[c]||String(c).replaceAll('_','/'));
    const concepts=inferConcepts(r.line,categories);
    const questions=inferQuestions(r.line,categories,concepts);
    const s={id:r.id,personId:r.person,person:p.name,time:p.time||'',year:p.year,loc:p.loc||'',order:r.order||'',text:r.line||'',reference:r.reference||'',categories,concepts,allTags:uniq([...categories,...concepts]),questions,movement:p.movement,summary:summaryFor(r.line,categories,concepts)};
    s.search=[s.text,s.person,s.time,s.reference,s.movement,s.summary,...s.allTags,...s.questions].join(' ').toLowerCase(); return s;
  });
  const byId=Object.fromEntries(statements.map(s=>[s.id,s]));
  const relations=raw.links.filter(l=>byId[l.l0]&&byId[l.l1]).map((l,i)=>({id:i,source:l.l0,target:l.l1,type:l.type==='p'?'support':'challenge'}));
  return finish({people,statements,relations});
}
function finish(db){
  db.peopleById=Object.fromEntries(db.people.map(p=>[p.id,p])); db.statementsById=Object.fromEntries(db.statements.map(s=>[s.id,s])); db.byPerson={}; db.out={}; db.in={};
  db.statements.forEach(s=>(db.byPerson[s.personId]||=[]).push(s)); db.relations.forEach(r=>{(db.out[r.source]||=[]).push(r);(db.in[r.target]||=[]).push(r);});
  db.concepts=counts(db.statements.flatMap(s=>s.concepts)).map(([name,count])=>({name,count})); db.questions=counts(db.statements.flatMap(s=>s.questions)).map(([name,count])=>({name,count})); db.domains=counts(db.statements.flatMap(s=>s.categories)).map(([name,count])=>({name,count}));
  db.routes=ROUTES.map(r=>({...r,ids:db.statements.filter(s=>r.keys.some(k=>s.search.includes(k))).sort(sortChrono).map(s=>s.id)})); return db;
}
function setDB(db){ DB=db; render(); inspectOverview(); }
function yearOf(t=''){ const m=String(t).match(/\d+/); if(!m)return null; let y=Number(m[0]); if(String(t).includes('BC'))y=-y; return y; }
function movementOf(p){ const n=p.name,y=yearOf(p.time); if(['Thales','Anaximander','Anaximenes'].includes(n))return'presocratic/cosmology'; if(n==='Pythagoras')return'pythagorean/number'; if(n==='Xenophanes')return'presocratic/fallibilism'; if(n==='Heraclitus')return'presocratic/becoming'; if(['Parmenides','Zeno of Elea'].includes(n))return'eleatic/being'; if(['Leucippus & Democritus','Epicurus'].includes(n))return'atomism/materialism'; if(n==='Socrates')return'socratic/ethics'; if(n==='Plato')return'platonic/forms'; if(n==='Aristotle')return'aristotelian/worldliness'; if(['Diogenes','Pyrrho','Stoics (Zeno of Citium et al)','Timon of Phlius','Plotinus'].includes(n))return'hellenistic/late ancient'; if(['Saint Augustine','John Scotus Erigena','Saint Anselm','Thomas Aquinas','William of Ockham'].includes(n))return'medieval/reason faith'; if(y<1700)return'early modern/metaphysics'; if(y<1800)return'enlightenment/empiricism politics'; if(y<1870)return'nineteenth/history critique'; if(y<1930)return'modern/language science'; return'contemporary/analytic continental'; }
function inferConcepts(text='',cats=[]){ const l=String(text).toLowerCase(), out=[]; const add=(c,rx)=>{if(rx.test(l))out.push(c)}; add('time',/\btime\b|timeless|eternal|present|duration|tempor/);add('change',/change|flux|becoming|evolv|process/);add('nature',/nature|natural|world|universe|earth|species/);add('matter',/matter|material|atom|particle|body|corporeal/);add('space',/space|location|world|universe/);add('mind',/mind|mental|conscious|intellect|thought|subject|awareness/);add('body',/body|bodies|corporeal|brain/);add('self',/self|subject|identity|person|soul/);add('reason',/reason|rational|logic|logical|mathemat|proof|deduc/);add('experience',/experience|sens|observ|perception|empirical|impression/);add('knowledge',/knowledge|know|truth|certainty|doubt|belief|explanation/);add('truth',/truth|true|false|certainty|proof/);add('science',/science|scientific|experiment|method|hypothesis|prediction|theory/);add('language',/language|word|speech|writing|sign|symbol|meaning|reference|discourse/);add('art',/art|aesthetic|beauty|poetry|tragedy|image|representation|sublime|illusion/);add('history',/history|historical|generation|past|civilization|tradition/);add('religion',/god|divine|religion|faith|soul|evil|theology/);add('morality',/moral|virtue|good|evil|right|wrong|duty|integrity/);add('justice',/justice|injustice|right|rights|law|equality|fair/);add('society',/society|social|community|public|private|civilization|custom/);add('government',/government|state|authority|sovereign|law|ruler|politic|citizen/);add('power',/power|authority|dominat|control|discipline|govern/);add('freedom',/freedom|free|liberty|will|choice|necessity/);add('death',/death|mortality|die|damned/);add('desire',/desire|passion|pleasure|appetite|emotion|fear|drive/);add('gender',/women|woman|female|male|gender|sex|femin/);add('math',/math|number|geometry|calculation/);add('causality',/cause|effect|causal|causation/);add('machine',/machine|mechanism|mechanical/); if(cats.includes('aesthetics'))out.push('art'); if(cats.includes('politics'))out.push('society','government'); if(cats.includes('theology/religion'))out.push('religion'); return uniq(out); }
function inferQuestions(line='',cats=[],concepts=[]){ const t=new Set(concepts), c=new Set(cats), l=String(line).toLowerCase(), out=[]; const add=x=>{if(!out.includes(x))out.push(x)}; if(c.has('ontology/metaphysics')||['nature','matter','space','mind','body','self','causality','machine'].some(x=>t.has(x)))add('What exists?'); if(c.has('epistemology')||['knowledge','truth','reason','experience','science','language'].some(x=>t.has(x)))add('How can we know?'); if(c.has('ethics')||['morality','justice','death','desire','freedom'].some(x=>t.has(x)))add('How should one live?'); if(c.has('politics')||['society','government','power'].some(x=>t.has(x)))add('How should society be governed?'); if(c.has('aesthetics')||t.has('art'))add('What does art do?'); if(c.has('theology/religion')||t.has('religion'))add('What is God?'); if(t.has('time')||t.has('change'))add('What is time?'); if(t.has('language'))add('What does language mean?'); if(t.has('science'))add('What is science?'); if(t.has('gender'))add('What is gender?'); if(t.has('freedom'))add('What is freedom?'); if(t.has('mind')||/consciousness|subject/.test(l))add('What is mind?'); return out.length?out.slice(0,5):['What is at stake?']; }
function summaryFor(line='',cats=[],concepts=[]){ const l=String(line).toLowerCase(); for(const [rx,g] of [[/time|change|flux|becoming|eternal/,'reality read through becoming'],[/language|word|speech|sign|meaning|discourse/,'meaning mediated by signs'],[/art|beauty|poetry|tragedy|image|illusion/,'representation tests reality'],[/science|experiment|method|prediction|theory/,'knowledge disciplined by method'],[/gender|women|female|male|sex/,'identity made philosophically visible'],[/government|state|power|law|society/,'order explained through power'],[/god|religion|faith|soul|evil/,'divinity anchors the system'],[/reason|logic|math|proof/,'reason seeks stable form'],[/experience|sense|observ|perception/,'knowledge begins at its limit'],[/death|mortality/,'death reframes value'],[/freedom|liberty|will/,'freedom tested by necessity'],[/truth|certainty|doubt/,'truth tested by doubt'],[/nature|matter|atom|machine/,'nature becomes explanatory ground']]) if(rx.test(l))return g; if(cats.includes('ethics'))return'thought becomes a rule of life'; if(cats.includes('epistemology'))return'knowledge defined by its conditions'; if(cats.includes('ontology/metaphysics'))return'being reduced to first principles'; return'claim positioned in the map'; }
function sortChrono(a,b){return(a.year??0)-(b.year??0)||a.personId-b.personId||Number(a.order||0)-Number(b.order||0)} function relCount(id){return(DB.out[id]?.length||0)+(DB.in[id]?.length||0)} function sortFn(a,b){if(S.sort==='author')return a.person.localeCompare(b.person)||Number(a.order||0)-Number(b.order||0); if(S.sort==='relations')return relCount(b.id)-relCount(a.id); return sortChrono(a,b)}
function visibleStatements(){ const q=S.q.toLowerCase(); return DB.statements.filter(s=>{ if(S.person!=null&&s.personId!==S.person)return false; if(S.concept&&!s.concepts.includes(S.concept))return false; if(S.problem&&!s.questions.includes(S.problem))return false; if(S.relation!=='all'){const rs=[...(DB.out[s.id]||[]),...(DB.in[s.id]||[])]; if(!rs.some(r=>r.type===S.relation))return false;} return !q||s.search.includes(q); }).sort(sortFn); }

function render(){ if(!DB)return; renderTop(); renderRail(); const st=visibleStatements(); $('#viewTitle').textContent=title(); $('#sub').textContent=`${st.length} visible · ${DB.people.length} authors · ${DB.statements.length} postulates · ${DB.relations.length} relations`; const views={atlas:viewAtlas,index:viewIndex,routes:viewRoutes,postulates:viewPostulates,graph:viewGraph,tensions:viewTensions,compare:viewCompare,upload:viewUpload}; $('#content').innerHTML=(views[S.view]||viewAtlas)(); $('#mobileNav').innerHTML=nav(true); attachUpload(); if(S.view==='atlas'||S.view==='graph')requestAnimationFrame(drawGraph); if(!S.statement) inspectOverview(); }
function title(){return({atlas:'Map',index:'Index',routes:'Routes',postulates:'Claims',graph:'Graph',tensions:'Tensions',compare:'Compare',upload:'Upload'})[S.view]||'Atlas'}
function renderTop(){ $('#stats').innerHTML=`<div class="stat"><strong>${DB.people.length}</strong><span>authors</span></div><div class="stat"><strong>${DB.statements.length}</strong><span>claims</span></div><div class="stat"><strong>${DB.relations.length}</strong><span>links</span></div>`; $('#nav').innerHTML=nav(false); const f=[`<span class="eyebrow">Filters</span>`]; if(S.q)f.push(`<button class="chip active" data-act="clear" data-val="q">search: ${esc(S.q)} ×</button>`); if(S.concept)f.push(`<button class="chip active" data-act="clear" data-val="concept">concept: ${esc(pretty(S.concept))} ×</button>`); if(S.problem)f.push(`<button class="chip active" data-act="clear" data-val="problem">question: ${esc(S.problem)} ×</button>`); if(S.person!=null)f.push(`<button class="chip active" data-act="clear" data-val="person">author: ${esc(DB.peopleById[S.person]?.name)} ×</button>`); f.push(`<button class="chip ${S.relation==='all'?'active':''}" data-act="relation" data-val="all">all</button><button class="chip ${S.relation==='support'?'active':''}" data-act="relation" data-val="support">● supports</button><button class="chip ${S.relation==='challenge'?'active':''}" data-act="relation" data-val="challenge">● challenges</button>`); $('#activeBar').innerHTML=f.join(''); }
function nav(mobile){ const items=mobile?[['atlas','Map'],['index','Index'],['routes','Routes'],['tensions','Tense'],['compare','Compare']]:[['atlas','Map'],['index','Index'],['routes','Routes'],['postulates','Claims'],['graph','Graph'],['tensions','Tensions'],['compare','Compare'],['upload','Upload']]; return items.map(([id,t])=>`<button class="viewBtn ${S.view===id?'active':''}" data-act="view" data-val="${id}">${t}</button>`).join('') }
function renderRail(){ const st=visibleStatements(); const authors=counts(st.map(s=>s.person)).slice(0,14); const concepts=counts(st.flatMap(s=>s.concepts)).slice(0,12); const questions=counts(st.flatMap(s=>s.questions)).slice(0,10); let html=''; if(S.view==='index'){ const list=S.indexType==='concept'?DB.concepts:DB.questions; html+=`<div class="railSection"><div class="railTitle">Index mode</div><div class="miniTabs"><button class="chip ${S.indexType==='concept'?'active':''}" data-act="view" data-val="index" data-kind="concept">Concepts</button><button class="chip ${S.indexType==='problem'?'active':''}" data-act="view" data-val="index" data-kind="problem">Questions</button></div></div><div class="railSection"><div class="railTitle">${S.indexType==='concept'?'Concepts':'Questions'}</div><div class="railList">${list.slice(0,28).map(i=>`<button class="railRow ${S.indexKey===i.name?'active':''}" data-act="index" data-kind="${S.indexType}" data-val="${esc(i.name)}"><b>${esc(S.indexType==='concept'?pretty(i.name):i.name)}</b><span>${i.count}</span></button>`).join('')}</div></div>`; } else { html+=`<div class="railSection"><div class="railTitle">Authors in view</div><div class="railList">${authors.map(([name,count])=>{const p=DB.people.find(x=>x.name===name);return`<button class="railRow ${S.person===p?.id?'active':''}" data-act="person" data-val="${p?.id??''}"><b>${esc(name)}</b><span>${count}</span></button>`}).join('')}</div></div><div class="railSection"><div class="railTitle">Concepts in view</div><div class="railList">${concepts.map(([name,count])=>railRow(name,count,'concept')).join('')}</div></div><div class="railSection"><div class="railTitle">Questions in view</div><div class="railList">${questions.map(([name,count])=>railRow(name,count,'problem')).join('')}</div></div>`; } html+=`<div class="railSection"><div class="railTitle">Routes</div><div class="railList">${DB.routes.slice(0,8).map(r=>`<button class="railRow ${S.route===r.id?'active':''}" data-act="route" data-val="${esc(r.id)}"><b>${esc(r.title)}</b><span>${r.ids.length}</span></button>`).join('')}</div></div>`; $('#rail').innerHTML=html; }
function railRow(name,count,kind){ const active=kind==='concept'?S.concept===name:S.problem===name; return `<button class="railRow ${active?'active':''}" data-act="filter" data-kind="${kind}" data-val="${esc(name)}"><b>${esc(kind==='concept'?pretty(name):name)}</b><span>${count}</span></button>`; }

function viewAtlas(){ const st=visibleStatements(); return `<div class="grid cols2"><div class="card"><div class="panelTitle"><div><h2>Relation map</h2><p>Chronology left to right. Domains form bands. Green supports; red challenges.</p></div>${sortTools()}</div><div class="graphBox"><svg id="graph"></svg></div></div><div class="grid"><div class="card"><div class="microTitle">Concepts in current view</div><div class="heat">${heat(counts(st.flatMap(s=>s.concepts)).slice(0,16),'concept')}</div></div><div class="card"><div class="microTitle">Questions in current view</div><div class="heat">${heat(counts(st.flatMap(s=>s.questions)).slice(0,12),'problem')}</div></div></div></div><div class="masonry" style="margin-top:10px">${st.slice(0,140).map(s=>`<div class="tile">${claimCard(s)}</div>`).join('')}</div>`; }
function viewPostulates(){ const st=visibleStatements(); return `<div class="panelTitle"><div><p>All active filters are applied, including selected author.</p></div>${sortTools()}</div><div class="masonry">${st.map(s=>`<div class="tile">${claimCard(s)}</div>`).join('')||empty('No postulates match.')}</div>`; }
function heat(items,kind){ const max=Math.max(1,...items.map(x=>x[1]||x.count)); return items.map(x=>{const name=x.name||x[0], count=x.count||x[1]; return `<button data-act="filter" data-kind="${kind}" data-val="${esc(name)}"><b>${esc(kind==='concept'?pretty(name):name)}</b><p>${count} postulates</p><div class="bar"><i style="width:${Math.round(count/max*100)}%"></i></div></button>`}).join(''); }
function sortTools(){return`<div class="semantic"><button class="chip ${S.sort==='chrono'?'active':''}" data-act="sort" data-val="chrono">chrono</button><button class="chip ${S.sort==='author'?'active':''}" data-act="sort" data-val="author">author</button><button class="chip ${S.sort==='relations'?'active':''}" data-act="sort" data-val="relations">relations</button></div>`}
function claimCard(s){ const rels=[...(DB.out[s.id]||[]),...(DB.in[s.id]||[])].slice(0,3); const concepts=s.concepts.slice(0,4).map(pretty).join(' · '); return `<article class="claim" data-act="statement" data-val="${s.id}"><div class="claimTop"><div class="claimAuthor"><b>${esc(s.person)}</b></div><div class="claimDate">${esc(s.time)}</div></div><div class="claimIntro"><span class="claimSummary">${esc(s.summary)}</span>${concepts?`<span class="conceptMono">${esc(concepts)}</span>`:''}</div><div class="claimText">${esc(s.text)}</div><div class="taxonomy"><div class="taxRow"><div class="taxLabel">Domain</div><div class="domains">${domainMarks(s.categories)}</div></div><div class="taxRow"><div class="taxLabel">Asks</div><div class="questions">${s.questions.slice(0,3).map(q=>`<span class="question">${esc(q)}</span>`).join('')}</div></div></div>${rels.length?`<div class="relationList">${rels.map(r=>relationItem(r,s.id)).join('')}</div>`:''}</article>`; }
function domainMarks(cats){ return cats.map(c=>`<span class="domain"><i style="background:${CAT_COLOR[c]||'var(--muted)'}"></i>${esc(CAT_LABEL[c]||pretty(c))}</span>`).join(''); }
function relationItem(r,focus){ const o=DB.statementsById[r.source===focus?r.target:r.source]; const mark=r.type==='support'?'+':'−'; return `<div class="relationItem ${r.type}" data-act="statement" data-val="${o.id}"><span class="relMark">${mark}</span><span><b>${esc(o.person)}</b> — ${esc(o.text)}</span></div>`; }
function pretty(s){return String(s).replaceAll('_',' ').replaceAll('/',' · ')} function empty(t){return`<div class="empty">${esc(t)}</div>`}
function viewIndex(){ const type=S.indexType||'concept', list=type==='concept'?DB.concepts:DB.questions, key=S.indexKey||(type==='concept'?S.concept:S.problem)||list[0]?.name; S.indexKey=key; return `<div>${indexDetail(type,key)}</div>`; }
function indexDetail(type,key){ const st=DB.statements.filter(s=>type==='concept'?s.concepts.includes(key):s.questions.includes(key)).filter(s=>!S.person||s.personId===S.person).sort(sortFn); const authors=counts(st.map(s=>s.person)).slice(0,24); const adj=counts(st.flatMap(s=>type==='concept'?s.questions:s.concepts)).slice(0,20); return `<div class="grid"><div class="card"><div class="panelTitle"><div><h2>${esc(type==='concept'?pretty(key):key)}</h2><p>${st.length} filtered postulates · ${authors.length} authors. Author clicks preserve active filters.</p></div>${sortTools()}</div></div><div class="grid cols2"><div class="card"><div class="microTitle">Authors</div><div class="heat">${heatPeople(authors)}</div></div><div class="card"><div class="microTitle">${type==='concept'?'Adjacent questions':'Adjacent concepts'}</div><div class="heat">${heat(adj,type==='concept'?'problem':'concept')}</div></div></div>${groupByAuthor(st)}</div>`; }
function heatPeople(items){ const max=Math.max(1,...items.map(x=>x[1])); return items.map(([name,count])=>{const p=DB.people.find(x=>x.name===name); return `<button data-act="person" data-val="${p?.id??''}"><b>${esc(name)}</b><p>${count} postulates</p><div class="bar"><i style="width:${Math.round(count/max*100)}%"></i></div></button>`}).join('') }
function groupByAuthor(st){ const groups=Object.values(st.reduce((a,s)=>((a[s.person]||=[]).push(s),a),{})).sort((a,b)=>(a[0].year??0)-(b[0].year??0)); return `<div class="masonry">${groups.map(g=>`<div class="tile"><div class="group"><div class="groupHead"><b data-act="person" data-val="${g[0].personId}">${esc(g[0].person)}</b><span>${esc(g[0].time)} · ${g.length}</span></div><div class="postulates">${g.map(s=>`<div class="postulate" data-act="statement" data-val="${s.id}">${esc(s.text)}</div>`).join('')}</div></div></div>`).join('')}</div>`; }
function viewRoutes(){ const r=DB.routes.find(x=>x.id===S.route)||DB.routes[0], st=r.ids.map(id=>DB.statementsById[id]).filter(s=>matchesActive(s)).sort(sortFn); const authors=counts(st.map(s=>s.person)).slice(0,32); return `<div class="grid"><div class="routeStrip">${DB.routes.map(x=>`<button class="routeCard ${x.id===r.id?'active':''}" data-act="route" data-val="${esc(x.id)}"><h3>${esc(x.title)}</h3><p>${esc(x.thesis)}</p><p>${x.ids.length} postulates</p></button>`).join('')}</div><div class="card"><div class="panelTitle"><div><h2>${esc(r.title)}</h2><p>${esc(r.thesis)}</p></div>${sortTools()}</div></div><div class="timeline">${authors.map(([name,count])=>routeAuthor(name,count,st)).join('')}</div><div class="card"><div class="microTitle">Route postulates</div>${groupByAuthor(st)}</div></div>`; }
function matchesActive(s){ return (!S.concept||s.concepts.includes(S.concept))&&(!S.problem||s.questions.includes(S.problem))&&(!S.person||s.personId===S.person); }
function routeAuthor(name,count,st){ const p=DB.people.find(x=>x.name===name), ss=st.filter(s=>s.person===name).slice(0,3); return `<div class="step"><h3 data-act="person" data-val="${p?.id??''}">${esc(name)}</h3><p>${count} postulates</p>${ss.map(s=>`<div class="postulate" data-act="statement" data-val="${s.id}">${esc(s.text)}</div>`).join('')}</div>`; }
function viewGraph(){return`<div class="card"><div class="panelTitle"><div><h2>Relation graph</h2><p>Filtered by active search/concept/question/author.</p></div>${sortTools()}</div><div class="graphBox"><svg id="graph"></svg></div></div>`}
function viewTensions(){ let rels=DB.relations.filter(r=>r.type==='challenge').filter(r=>matchesActive(DB.statementsById[r.source])||matchesActive(DB.statementsById[r.target])); return `<div class="masonry">${rels.slice(0,180).map(r=>{const a=DB.statementsById[r.source],b=DB.statementsById[r.target];return`<div class="tile"><div class="card"><div class="microTitle">Challenge</div><div class="relationItem challenge" data-act="statement" data-val="${a.id}"><span class="relMark">−</span><span><b>${esc(a.person)}</b> — ${esc(a.text)}</span></div><div class="relationItem challenge" data-act="statement" data-val="${b.id}"><span class="relMark">−</span><span><b>${esc(b.person)}</b> — ${esc(b.text)}</span></div></div></div>`}).join('')}</div>`}
function viewCompare(){ const ids=S.compare.length?S.compare:DB.people.slice(10,14).map(p=>p.id), people=ids.map(id=>DB.peopleById[id]).filter(Boolean); document.documentElement.style.setProperty('--cols', String(people.length)); return `<div class="grid"><div class="card"><h2>Compare</h2><p>Add authors from any card. Active filters still apply to postulate lists.</p></div><div class="masonry">${people.map(p=>`<div class="tile">${compareCol(p)}</div>`).join('')}</div><div class="card"><div class="microTitle">Question matrix</div>${compareMatrix(people)}</div></div>`}
function compareCol(p){ const st=(DB.byPerson[p.id]||[]).filter(matchesActive); return `<div class="card"><div class="contextHeader"><h3>${esc(p.name)}</h3><button class="chip" data-act="dropCompare" data-val="${p.id}">remove</button></div><p>${esc(p.time)}</p><div class="taxonomy"><div class="taxRow"><div class="taxLabel">Ideas</div><div class="domains">${counts(st.flatMap(s=>s.concepts)).slice(0,10).map(([t,c])=>`<span class="conceptMono">${esc(pretty(t))} ${c}</span>`).join('')}</div></div><div class="taxRow"><div class="taxLabel">Asks</div><div class="questions">${counts(st.flatMap(s=>s.questions)).slice(0,6).map(([t,c])=>`<span class="question">${esc(t)} ${c}</span>`).join('')}</div></div></div><div class="postulates">${st.slice(0,12).map(s=>`<div class="postulate" data-act="statement" data-val="${s.id}">${esc(s.text)}</div>`).join('')}</div></div>`; }
function compareMatrix(people){ const qs=uniq(people.flatMap(p=>(DB.byPerson[p.id]||[]).filter(matchesActive).flatMap(s=>s.questions))).slice(0,18); return `<div class="matrix"><div class="cell"></div>${people.map(p=>`<div class="cell"><b>${esc(p.name)}</b></div>`).join('')}${qs.map(q=>`<div class="cell">${esc(q)}</div>${people.map(p=>{const n=(DB.byPerson[p.id]||[]).filter(matchesActive).filter(s=>s.questions.includes(q)).length; return `<div class="cell ${n?'hot':''}" style="--p:${Math.min(80,n*16)}">${n||''}</div>`}).join('')}`).join('')}</div>`; }
function viewUpload(){return`<div class="card"><h2>Upload</h2><p>Optional. The app uses philosophers.json as ground truth.</p>${uploadBox()}</div>`}
function drawGraph(){ const svg=$('#graph'); if(!svg||!DB)return; const fs=visibleStatements().slice(0,240), ids=new Set(fs.map(s=>s.id)); let rels=DB.relations.filter(r=>ids.has(r.source)&&ids.has(r.target)); if(S.relation!=='all')rels=rels.filter(r=>r.type===S.relation); rels=rels.slice(0,460); const w=svg.clientWidth||900,h=svg.clientHeight||440, years=DB.people.map(p=>p.year).filter(Number.isFinite), min=Math.min(...years), max=Math.max(...years), span=max-min||1; const band=Object.fromEntries(CAT_ORDER.map((c,i)=>[c,(i+1)/(CAT_ORDER.length+1)])), pos={}; fs.forEach((s,i)=>{const p=DB.peopleById[s.personId], x=32+(((p.year??0)-min)/span)*(w-64), y=(band[s.categories[0]]||.55)*h+((i%9)-4)*4.5; pos[s.id]=[clamp(x,18,w-18),clamp(y,18,h-18)]}); const edges=rels.map(r=>{const a=pos[r.source],b=pos[r.target];return a&&b?`<line class="edge ${r.type}" x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke-width="${r.type==='challenge'?1.45:1}"/>`:''}).join(''); const nodes=fs.map(s=>{const [x,y]=pos[s.id], color=CAT_COLOR[s.categories[0]]||'var(--ink)'; return `<g class="node" data-act="statement" data-val="${s.id}"><circle cx="${x}" cy="${y}" r="${S.statement===s.id?6.5:4}" fill="${color}"><title>${esc(s.person)} — ${esc(s.text)}</title></circle></g>`}).join(''); const labels=uniq(fs.map(s=>s.personId)).slice(0,72).map(id=>{const s=fs.find(x=>x.personId===id),p=pos[s.id];return`<text class="svglabel" x="${p[0]+6}" y="${p[1]-6}">${esc(s.person)}</text>`}).join(''); svg.innerHTML=edges+nodes+labels; }
function inspectOverview(){ if(!DB)return; $('#context').innerHTML=`<div class="contextPanel"><div class="contextBlock"><div class="microTitle">Current view</div>${summaryStats()}</div><div class="contextBlock"><div class="microTitle">Routes</div><div class="railList">${DB.routes.map(r=>`<button class="railRow ${S.route===r.id?'active':''}" data-act="route" data-val="${esc(r.id)}"><b>${esc(r.title)}</b><span>${r.ids.length}</span></button>`).join('')}</div></div><div class="contextBlock"><div class="microTitle">Leading questions</div><div class="semantic">${DB.questions.slice(0,10).map(q=>`<button class="chip" data-act="filter" data-kind="problem" data-val="${esc(q.name)}">${esc(q.name)} · ${q.count}</button>`).join('')}</div></div>${uploadBox()}</div>`; attachUpload(); }
function summaryStats(){ const st=visibleStatements(); return `<div class="heat"><button><b>${st.length}</b><p>visible postulates</p></button><button><b>${counts(st.map(s=>s.person)).length}</b><p>authors</p></button><button><b>${counts(st.flatMap(s=>s.concepts)).length}</b><p>concepts</p></button></div>`; }
function inspectPerson(id){ const p=DB.peopleById[id], st=(DB.byPerson[id]||[]).filter(matchesActive); $('#context').innerHTML=`<div class="contextPanel"><div class="contextBlock"><div class="contextHeader"><h3>${esc(p.name)}</h3><button class="chip" data-act="compare" data-val="${id}">compare</button></div><p>${esc(p.time)} · ${esc(p.movement)}</p><p>${st.length} postulates with current filters.</p></div><div class="contextBlock"><div class="microTitle">Concept signature</div><div class="domains">${counts(st.flatMap(s=>s.concepts)).slice(0,14).map(([t,c])=>`<span class="conceptMono">${esc(pretty(t))} ${c}</span>`).join('')}</div></div><div class="contextBlock"><div class="microTitle">Filtered postulates</div><div class="postulates">${st.slice(0,14).map(s=>`<div class="postulate" data-act="statement" data-val="${s.id}">${esc(s.text)}</div>`).join('')}</div></div></div>`; }
function inspectStatement(id){ const s=DB.statementsById[id]; if(!s)return; S.statement=id; const rels=[...(DB.out[id]||[]),...(DB.in[id]||[])]; $('#context').innerHTML=`<div class="contextPanel"><div class="contextBlock"><div class="contextHeader"><h3>${esc(s.person)}</h3><button class="chip" data-act="compare" data-val="${s.personId}">compare</button></div><p>${esc(s.time)} · ${esc(s.movement)}</p><div class="claimIntro"><span class="claimSummary">${esc(s.summary)}</span>${s.concepts[0]?`<span class="conceptMono">${esc(pretty(s.concepts[0]))}</span>`:''}</div><div class="contextPostulate">${esc(s.text)}</div></div><div class="contextBlock"><div class="microTitle">Semantics</div><div class="taxonomy"><div class="taxRow"><div class="taxLabel">Domain</div><div>${domainMarks(s.categories)}</div></div><div class="taxRow"><div class="taxLabel">Ideas</div><div>${s.concepts.map(c=>`<button class="conceptMono" data-act="filter" data-kind="concept" data-val="${esc(c)}">${esc(pretty(c))}</button>`).join('')}</div></div><div class="taxRow"><div class="taxLabel">Asks</div><div>${s.questions.map(q=>`<button class="question" data-act="filter" data-kind="problem" data-val="${esc(q)}">${esc(q)}</button>`).join('')}</div></div></div></div><div class="contextBlock"><div class="microTitle">Supports</div><div class="relationList">${rels.filter(r=>r.type==='support').map(r=>relationItem(r,id)).join('')||'<p>None.</p>'}</div></div><div class="contextBlock"><div class="microTitle">Challenges</div><div class="relationList">${rels.filter(r=>r.type==='challenge').map(r=>relationItem(r,id)).join('')||'<p>None.</p>'}</div></div></div>`; }
function uploadBox(){return`<div class="drop"><b>Upload data</b><p>Optional JSON replacement.</p><input id="fileInput" type="file" accept=".json,application/json"></div>`} function attachUpload(){const input=$('#fileInput'); if(!input)return; input.onchange=async e=>{const f=e.target.files[0]; if(!f)return; const txt=await f.text(); try{setDB(buildDB(JSON.parse(txt)))}catch(err){alert('Only original JSON upload is supported in this refined build: '+err.message)}}}
